project:
  type: website
  output-dir: ../docs
  resources:
  - "./assets"

website:
  title: "Home" # Change this
  # favicon: assets/icon.png # Can create an icon for your website (What displays on the tab)
  navbar:
    left:
      - href: papers.qmd # Delete these lines to remove the "Papers" section
        text: Papers # Delete these lines to remove the "Papers" section
      - href: teaching.qmd # Delete these lines to remove the "Papers" section
        text: Teaching # Delete these lines to remove the "Papers" section
      - href: outreach.qmd # Delete these lines to remove the "Papers" section
        text: Outreach # Delete these lines to remove the "Papers" section
      - href: assets/CV.pdf # Update this file to your CV
        text: CV
      - href: calligraphy.qmd # Delete these lines to remove the "Papers" section
        text: Calligraphy # Delete these lines to remove the "Papers" section
      # Can add more pages here

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
